# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e59f01637db164c6e326068a17304ae1fc49c305b0bd7a7813ef64342902cef185611748177201156609a6e465e5ea327a174fac6ae11e835b2c01f9577ad98

test:
  secret_key_base: 6268de32de668ba2f8446b498cf41bb3cdfa8ebc6074dbc731991cfa603b51517210bf12bc878b862f05b3d499d5c3256bb432a0d0f56a9ceeb517d8236bc867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
