# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 531c43b3ec37828b3c955ed51c60e73df57222abf4d372f729572658ee96c220766db825f49ad6a5c2abf9a37bfc968c9d7c6f4e990a87c9352829e49fad0562

test:
  secret_key_base: 102fc5b2c23330806114516d8fd097d8b27a3e066a36c59266784cb51c3a25871e7e2e416ed0b2bdb29e7b48a242b1e00427308322ff67552c434db1e0452106

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
